name: Python Checks

on:
  workflow_call:
    inputs:
      directory:
        description: Folder containing the Python project
        required: true
        type: string
      python-version:
        description: Python version to use
        required: false
        type: string
        default: "3.14"

jobs:
  pre-commit:
    name: Pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - uses: pre-commit/action@v3.0.1
        env:
          SKIP: terraform_fmt

  pytest:
    name: Pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install dependencies
        working-directory: ${{ inputs.directory }}
        run: pip install -e ".[dev]"

      - name: Run tests
        working-directory: ${{ inputs.directory }}
        run: pytest tests/ -v
