name: QA App Backend

on:
  pull_request:
    branches: [main]
    paths: [backend/**]
  push:
    branches: [main]
    paths: [backend/**]

jobs:
  python-checks:
    uses: ./.github/workflows/python-checks.yml
    with:
      directory: backend
      python-version: "3.14"

  docker:
    uses: ./.github/workflows/docker-build.yml
    needs:
      - python-checks
    with:
      directory: backend
      ecr-repo: travel-booking-app-backend
      aws-region: eu-west-1
      role-to-assume: arn:aws:iam::381665779871:role/travel-booking-deployment-role
      publish: ${{ github.ref == 'refs/heads/main' }}
    permissions:
      contents: read
      id-token: write
